// ===== 英語（外国語）のコンテンツ =====
// 日本の小学生向け。学習指導要領では3・4年で外国語活動、5・6年で教科としての外国語。
// そのため grade 3 から出題し、3・4年は身近な単語中心、5・6年で文や表現を扱う。
//
// word: 英語 / grade: 出題を始める学年
// ja / es: 学習者の母語ラベル。表示言語に合わせて buildEnglishPool() が選ぶ。
//
// ⚠️ **問題本体は英語側（word / text / answer / options）で、母語ラベルは訳にすぎない。**
//    だから ja の隣に es を置くだけで、このバンクはそのままスペイン語話者向けの
//    英語教材になる（es-handoff.md §2）。語を足すときは ja と es を必ず両方書くこと。
//    片方だけだと t() と同じで日本語が静かに混ざる。`node tools/check_i18n_keys.js` が検出する。
//
// ⚠️ EN_WORDS の母語ラベルは、そのまま4択の選択肢になる（他の語のラベルが誤答に回る）。
//    **同じ訳語を2語に付けないこと。** 正解が2つある問題になる。

const EN_WORDS = [
  // 3年：身のまわりのもの・色・数
  { grade: 3, word: "apple", ja: "りんご", es: "manzana", de: "der Apfel" },
  { grade: 3, word: "dog", ja: "いぬ", es: "perro", de: "der Hund" },
  { grade: 3, word: "cat", ja: "ねこ", es: "gato", de: "die Katze" },
  { grade: 3, word: "book", ja: "ほん", es: "libro", de: "das Buch" },
  { grade: 3, word: "red", ja: "あか", es: "rojo", de: "rot" },
  { grade: 3, word: "blue", ja: "あお", es: "azul", de: "blau" },
  { grade: 3, word: "green", ja: "みどり", es: "verde", de: "grün" },
  { grade: 3, word: "yellow", ja: "きいろ", es: "amarillo", de: "gelb" },
  { grade: 3, word: "one", ja: "1", es: "uno", de: "eins" },
  { grade: 3, word: "two", ja: "2", es: "dos", de: "zwei" },
  { grade: 3, word: "three", ja: "3", es: "tres", de: "drei" },
  { grade: 3, word: "school", ja: "がっこう", es: "colegio", de: "die Schule" },
  { grade: 3, word: "pencil", ja: "えんぴつ", es: "lápiz", de: "der Bleistift" },
  { grade: 3, word: "bag", ja: "かばん", es: "bolsa", de: "die Tasche" },
  { grade: 3, word: "water", ja: "みず", es: "agua", de: "das Wasser" },
  { grade: 3, word: "fish", ja: "さかな", es: "pez", de: "der Fisch" },
  { grade: 3, word: "bird", ja: "とり", es: "pájaro", de: "der Vogel" },
  { grade: 3, word: "tree", ja: "き", es: "árbol", de: "der Baum" },
  { grade: 3, word: "sun", ja: "たいよう", es: "sol", de: "die Sonne" },
  { grade: 3, word: "rain", ja: "あめ", es: "lluvia", de: "der Regen" },

  // 4年：曜日・食べ物・動作
  { grade: 4, word: "Monday", ja: "月よう日", es: "lunes", de: "Montag" },
  { grade: 4, word: "Sunday", ja: "日よう日", es: "domingo", de: "Sonntag" },
  { grade: 4, word: "breakfast", ja: "朝ごはん", es: "desayuno", de: "das Frühstück" },
  { grade: 4, word: "lunch", ja: "昼ごはん", es: "comida del mediodía", de: "das Mittagessen" },
  { grade: 4, word: "dinner", ja: "夕ごはん", es: "cena", de: "das Abendessen" },
  { grade: 4, word: "run", ja: "走る", es: "correr", de: "laufen" },
  { grade: 4, word: "swim", ja: "泳ぐ", es: "nadar", de: "schwimmen" },
  { grade: 4, word: "read", ja: "読む", es: "leer", de: "lesen" },
  { grade: 4, word: "write", ja: "書く", es: "escribir", de: "schreiben" },
  { grade: 4, word: "eat", ja: "食べる", es: "comer", de: "essen" },
  { grade: 4, word: "spring", ja: "春", es: "primavera", de: "der Frühling" },
  { grade: 4, word: "summer", ja: "夏", es: "verano", de: "der Sommer" },
  { grade: 4, word: "autumn", ja: "秋", es: "otoño", de: "der Herbst" },
  { grade: 4, word: "winter", ja: "冬", es: "invierno", de: "der Winter" },
  { grade: 4, word: "morning", ja: "朝", es: "mañana", de: "der Morgen" },
  { grade: 4, word: "night", ja: "夜", es: "noche", de: "die Nacht" },
  { grade: 4, word: "friend", ja: "友だち", es: "amigo", de: "der Freund" },
  { grade: 4, word: "family", ja: "家族", es: "familia", de: "die Familie" },
  { grade: 4, word: "teacher", ja: "先生", es: "profesor", de: "der Lehrer" },
  { grade: 4, word: "music", ja: "音楽", es: "música", de: "die Musik" },
  { grade: 4, word: "milk", ja: "ぎゅうにゅう", es: "leche", de: "die Milch" },
  { grade: 4, word: "rice", ja: "ごはん", es: "arroz", de: "der Reis" },
  { grade: 4, word: "egg", ja: "たまご", es: "huevo", de: "das Ei" },
  { grade: 4, word: "notebook", ja: "ノート", es: "cuaderno", de: "das Heft" },
  { grade: 4, word: "eraser", ja: "けしゴム", es: "goma de borrar", de: "der Radiergummi" },
  { grade: 4, word: "jump", ja: "とぶ", es: "saltar", de: "springen" },
  { grade: 4, word: "sing", ja: "うたう", es: "cantar", de: "singen" },
  { grade: 4, word: "dance", ja: "おどる", es: "bailar", de: "tanzen" },
  { grade: 4, word: "cook", ja: "りょうりする", es: "cocinar", de: "kochen" },
  { grade: 4, word: "sleep", ja: "ねる", es: "dormir", de: "schlafen" },

  // 5年：教科・場所・性質
  { grade: 5, word: "science", ja: "理科", es: "ciencias", de: "die Naturwissenschaft" },
  { grade: 5, word: "math", ja: "算数", es: "matemáticas", de: "die Mathematik" },
  { grade: 5, word: "hospital", ja: "病院", es: "hospital", de: "das Krankenhaus" },
  { grade: 5, word: "station", ja: "駅", es: "estación", de: "der Bahnhof" },
  { grade: 5, word: "library", ja: "図書館", es: "biblioteca", de: "die Bibliothek" },
  { grade: 5, word: "park", ja: "公園", es: "parque", de: "der Park" },
  { grade: 5, word: "country", ja: "国", es: "país", de: "das Land" },
  { grade: 5, word: "city", ja: "都市", es: "ciudad", de: "die Stadt" },
  { grade: 5, word: "beautiful", ja: "美しい", es: "hermoso", de: "schön" },
  { grade: 5, word: "difficult", ja: "むずかしい", es: "difícil", de: "schwierig" },
  { grade: 5, word: "important", ja: "大切な", es: "importante", de: "wichtig" },
  { grade: 5, word: "delicious", ja: "おいしい", es: "delicioso", de: "lecker" },
  { grade: 5, word: "favorite", ja: "お気に入りの", es: "favorito", de: "Lieblings-" },
  { grade: 5, word: "future", ja: "将来", es: "futuro", de: "die Zukunft" },
  { grade: 5, word: "dream", ja: "ゆめ", es: "sueño", de: "der Traum" },

  // 6年：抽象語・行事
  { grade: 6, word: "memory", ja: "思い出", es: "recuerdo", de: "die Erinnerung" },
  { grade: 6, word: "experience", ja: "経験", es: "experiencia", de: "die Erfahrung" },
  { grade: 6, word: "environment", ja: "環境", es: "medio ambiente", de: "die Umwelt" },
  { grade: 6, word: "culture", ja: "文化", es: "cultura", de: "die Kultur" },
  { grade: 6, word: "peace", ja: "平和", es: "paz", de: "der Frieden" },
  { grade: 6, word: "festival", ja: "祭り", es: "fiesta", de: "das Fest" },
  { grade: 6, word: "graduation", ja: "卒業", es: "graduación", de: "der Abschluss" },
  { grade: 6, word: "junior high school", ja: "中学校", es: "escuela secundaria", de: "die weiterführende Schule" },
  { grade: 6, word: "volunteer", ja: "ボランティア", es: "voluntario", de: "der Freiwillige" },
  { grade: 6, word: "president", ja: "大統領", es: "presidente", de: "der Präsident" },
];

// あいさつ・やりとり。text の ___ が空所。
// ja / es は解説にだけ使う（選択肢は英語なので、訳語が重複しても問題は壊れない）。
const EN_PHRASES = [
  { grade: 3, text: "How are you? — I'm ___, thank you.", answer: "fine",
    options: ["fine", "eat", "book", "red"], ja: "げんきです、ありがとう",
    es: "Estoy bien, gracias", de: "Wie geht es dir? — Mir geht es gut, danke." },
  { grade: 3, text: "___ morning!", answer: "Good",
    options: ["Good", "Many", "Very", "Some"], ja: "おはよう",
    es: "¡Buenos días!", de: "Guten Morgen!" },
  { grade: 3, text: "My ___ is Taro.", answer: "name",
    options: ["name", "color", "food", "book"], ja: "わたしの名前はタロウです",
    es: "Me llamo Taro", de: "Ich heiße Taro." },
  { grade: 3, text: "Thank you. — You're ___.", answer: "welcome",
    options: ["welcome", "sorry", "happy", "ready"], ja: "どういたしまして",
    es: "De nada", de: "Danke. — Gern geschehen." },
  { grade: 4, text: "___ do you like? — I like soccer.", answer: "What",
    options: ["What", "Who", "Where", "When"], ja: "何がすきですか",
    es: "¿Qué te gusta?", de: "Was magst du? — Ich mag Fußball." },
  { grade: 4, text: "___ is your birthday? — It's in May.", answer: "When",
    options: ["When", "What", "Who", "How"], ja: "たんじょう日はいつですか",
    es: "¿Cuándo es tu cumpleaños?", de: "Wann hast du Geburtstag? — Im Mai." },
  { grade: 4, text: "I ___ up at six.", answer: "get",
    options: ["get", "go", "make", "take"], ja: "6時に起きます",
    es: "Me levanto a las seis", de: "Ich stehe um sechs Uhr auf." },
  { grade: 4, text: "___ is the library? — It's near the park.", answer: "Where",
    options: ["Where", "What", "Why", "Who"], ja: "図書館はどこですか",
    es: "¿Dónde está la biblioteca?", de: "Wo ist die Bibliothek? — Sie ist in der Nähe des Parks." },
  { grade: 5, text: "I want ___ be a teacher.", answer: "to",
    options: ["to", "of", "in", "at"], ja: "先生になりたいです",
    es: "Quiero ser profesor", de: "Ich möchte Lehrer werden." },
  { grade: 5, text: "This is ___ favorite place.", answer: "my",
    options: ["my", "me", "I", "mine"], ja: "ここはわたしのお気に入りの場所です",
    es: "Este es mi lugar favorito", de: "Das ist mein Lieblingsort." },
  { grade: 5, text: "He ___ soccer every Sunday.", answer: "plays",
    options: ["plays", "play", "playing", "played"], ja: "彼は毎週日よう日にサッカーをします",
    es: "Él juega al fútbol todos los domingos", de: "Er spielt jeden Sonntag Fußball." },
  { grade: 5, text: "___ much is this? — It's 500 yen.", answer: "How",
    options: ["How", "What", "Who", "Where"], ja: "これはいくらですか",
    es: "¿Cuánto cuesta esto?", de: "Wie viel kostet das? — Es kostet 500 Yen." },
  { grade: 5, text: "Can you ___ me your pen?", answer: "lend",
    options: ["lend", "borrow", "buy", "give up"], ja: "ペンを貸してくれる？",
    es: "¿Me prestas tu bolígrafo?", de: "Kannst du mir deinen Stift leihen?" },
  { grade: 5, text: "I usually ___ breakfast at seven.", answer: "have",
    options: ["have", "has", "having", "had"], ja: "たいてい7時に朝食を食べます",
    es: "Normalmente desayuno a las siete", de: "Normalerweise frühstücke ich um sieben Uhr." },
  { grade: 5, text: "___ do you go to school? — By bus.", answer: "How",
    options: ["How", "What", "When", "Why"], ja: "どうやって学校に行きますか",
    es: "¿Cómo vas al colegio?", de: "Wie kommst du zur Schule? — Mit dem Bus." },
  { grade: 5, text: "She is good ___ playing the piano.", answer: "at",
    options: ["at", "in", "on", "for"], ja: "彼女はピアノをひくのが得意です",
    es: "A ella se le da bien tocar el piano", de: "Sie kann gut Klavier spielen." },
  { grade: 5, text: "There ___ two cats under the table.", answer: "are",
    options: ["are", "is", "am", "be"], ja: "テーブルの下にねこが2ひきいます",
    es: "Hay dos gatos debajo de la mesa", de: "Unter dem Tisch sind zwei Katzen." },
  { grade: 6, text: "I ___ to Kyoto last summer.", answer: "went",
    options: ["went", "go", "going", "goes"], ja: "去年の夏、京都に行きました",
    es: "El verano pasado fui a Kioto", de: "Letzten Sommer bin ich nach Kyoto gefahren." },
  { grade: 6, text: "My best ___ is the school festival.", answer: "memory",
    options: ["memory", "morning", "market", "minute"], ja: "一番の思い出は学園祭です",
    es: "Mi mejor recuerdo es la fiesta del colegio", de: "Meine schönste Erinnerung ist das Schulfest." },
  { grade: 6, text: "I want to ___ the environment.", answer: "protect",
    options: ["protect", "produce", "prepare", "present"], ja: "環境を守りたいです",
    es: "Quiero proteger el medio ambiente", de: "Ich möchte die Umwelt schützen." },
  { grade: 6, text: "We ___ enjoyed the trip.", answer: "all",
    options: ["all", "every", "each", "both"], ja: "わたしたちはみんな旅行を楽しみました",
    es: "Todos disfrutamos del viaje", de: "Wir haben alle die Reise genossen." },
  { grade: 6, text: "This book is ___ than that one.", answer: "more interesting",
    options: ["more interesting", "interesting", "most interesting", "interestinger"], ja: "この本はあの本より面白いです",
    es: "Este libro es más interesante que aquel", de: "Dieses Buch ist interessanter als jenes." },
  { grade: 6, text: "If it ___ tomorrow, we will stay home.", answer: "rains",
    options: ["rains", "rain", "rained", "raining"], ja: "もし明日雨が降ったら、家にいます",
    es: "Si mañana llueve, nos quedaremos en casa", de: "Wenn es morgen regnet, bleiben wir zu Hause." },
  { grade: 6, text: "I have ___ finished my homework.", answer: "already",
    options: ["already", "yet", "ever", "still"], ja: "もう宿題を終わらせました",
    es: "Ya he terminado los deberes", de: "Ich habe meine Hausaufgaben schon fertig gemacht." },
  { grade: 6, text: "This is the book ___ I read last week.", answer: "that",
    options: ["that", "who", "what", "where"], ja: "これは先週読んだ本です",
    es: "Este es el libro que leí la semana pasada", de: "Das ist das Buch, das ich letzte Woche gelesen habe." },
  { grade: 3, text: "Nice to ___ you.", answer: "meet",
    options: ["meet", "make", "read", "open"], ja: "はじめまして",
    es: "Encantado de conocerte", de: "Freut mich, dich kennenzulernen." },
  { grade: 3, text: "___ you like apples? — Yes, I do.", answer: "Do",
    options: ["Do", "Is", "Are", "Am"], ja: "りんごはすきですか",
    es: "¿Te gustan las manzanas?", de: "Magst du Äpfel? — Ja." },
  { grade: 3, text: "See ___ tomorrow!", answer: "you",
    options: ["you", "me", "it", "we"], ja: "また明日",
    es: "¡Hasta mañana!", de: "Bis morgen!" },
  { grade: 3, text: "Let's ___ soccer.", answer: "play",
    options: ["play", "eat", "read", "open"], ja: "サッカーをしよう",
    es: "Vamos a jugar al fútbol", de: "Lass uns Fußball spielen." },
  { grade: 3, text: "___ is this? — It's a cat.", answer: "What",
    options: ["What", "Who", "When", "Where"], ja: "これは何ですか",
    es: "¿Qué es esto?", de: "Was ist das? — Das ist eine Katze." },
  { grade: 3, text: "Here you ___.", answer: "are",
    options: ["are", "is", "am", "be"], ja: "はい、どうぞ",
    es: "Aquí tienes", de: "Bitte schön." },
  { grade: 4, text: "___ old are you? — I'm ten.", answer: "How",
    options: ["How", "What", "Who", "Why"], ja: "何さいですか",
    es: "¿Cuántos años tienes?", de: "Wie alt bist du? — Ich bin zehn." },
  { grade: 4, text: "I go to school ___ bike.", answer: "by",
    options: ["by", "in", "on", "to"], ja: "自転車で学校に行きます",
    es: "Voy al colegio en bici", de: "Ich fahre mit dem Fahrrad zur Schule." },
  { grade: 4, text: "She ___ a red bag.", answer: "has",
    options: ["has", "have", "having", "is"], ja: "彼女は赤いかばんを持っています",
    es: "Ella tiene una bolsa roja", de: "Sie hat eine rote Tasche." },
  { grade: 3, text: "I ___ a red pen.", answer: "have",
    options: ["have", "has", "is", "am"], ja: "赤いペンを持っています",
    es: "Tengo un bolígrafo rojo", de: "Ich habe einen roten Stift." },
  { grade: 3, text: "This ___ my dog.", answer: "is",
    options: ["is", "am", "are", "be"], ja: "これはわたしの犬です",
    es: "Este es mi perro", de: "Das ist mein Hund." },
  { grade: 3, text: "I ___ blue.", answer: "like",
    options: ["like", "likes", "liking", "liked"], ja: "青がすきです",
    es: "Me gusta el azul", de: "Ich mag Blau." },
  { grade: 3, text: "___ birthday!", answer: "Happy",
    options: ["Happy", "Good", "Nice", "Great"], ja: "たんじょう日おめでとう",
    es: "¡Feliz cumpleaños!", de: "Alles Gute zum Geburtstag!" },
  { grade: 3, text: "___ is the bag?", answer: "Where",
    options: ["Where", "What", "Who", "When"], ja: "かばんはどこですか",
    es: "¿Dónde está la bolsa?", de: "Wo ist die Tasche?" },
  { grade: 3, text: "I ___ swim.", answer: "can",
    options: ["can", "do", "am", "is"], ja: "わたしは泳げます",
    es: "Sé nadar", de: "Ich kann schwimmen." },
  { grade: 4, text: "I ___ a new bike.", answer: "want",
    options: ["want", "wants", "wanting", "wanted"], ja: "新しい自転車がほしいです",
    es: "Quiero una bici nueva", de: "Ich möchte ein neues Fahrrad." },
  { grade: 4, text: "She ___ my sister.", answer: "is",
    options: ["is", "are", "am", "be"], ja: "彼女はわたしの姉（妹）です",
    es: "Ella es mi hermana", de: "Sie ist meine Schwester." },
  { grade: 4, text: "I ___ like natto.", answer: "don't",
    options: ["don't", "isn't", "doesn't", "can't"], ja: "わたしは納豆がすきではありません",
    es: "No me gusta el natto", de: "Ich mag Natto nicht." },
  { grade: 4, text: "___ go to the park.", answer: "Let's",
    options: ["Let's", "Let", "Lets", "Letting"], ja: "公園に行こう",
    es: "Vamos al parque", de: "Lass uns in den Park gehen." },
  // could を外した。日本語は現在形だが "He could run fast." も正しい文になり、正解が2つあった
  { grade: 4, text: "He ___ run fast.", answer: "can",
    options: ["can", "cans", "canning", "is"], ja: "彼は速く走ることができます",
    es: "Él sabe correr rápido", de: "Er kann schnell laufen." },
  { grade: 4, text: "___ time is it?", answer: "What",
    options: ["What", "When", "Where", "Why"], ja: "何時ですか",
    es: "¿Qué hora es?", de: "Wie spät ist es?" },
  { grade: 3, text: "___ afternoon!", answer: "Good",
    options: ["Good", "Nice", "Fine", "Well"], ja: "こんにちは（午後のあいさつ）",
    es: "¡Buenas tardes!", de: "Guten Tag!" },
  { grade: 3, text: "Good ___! See you tomorrow.", answer: "night",
    options: ["night", "day", "time", "week"], ja: "おやすみなさい",
    es: "¡Buenas noches!", de: "Gute Nacht! Bis morgen." },
  { grade: 3, text: "___ you! — You're welcome.", answer: "Thank",
    options: ["Thank", "Think", "Take", "Talk"], ja: "ありがとう",
    es: "¡Gracias!", de: "Danke! — Gern geschehen." },
  { grade: 3, text: "I'm ___. — That's OK.", answer: "sorry",
    options: ["sorry", "sunny", "story", "start"], ja: "ごめんなさい",
    es: "Lo siento", de: "Es tut mir leid. — Schon gut." },
  { grade: 3, text: "I am ___ now.", answer: "hungry",
    options: ["hungry", "hungrily", "hunger", "hungering"], ja: "わたしは今おなかがすいています",
    es: "Ahora tengo hambre", de: "Ich habe jetzt Hunger." },
  { grade: 3, text: "___ you later!", answer: "See",
    options: ["See", "Sit", "Say", "Set"], ja: "またあとでね",
    es: "¡Hasta luego!", de: "Bis später!" },
  { grade: 3, text: "How ___ are you? — I'm eight.", answer: "old",
    options: ["old", "many", "long", "far"], ja: "何さいですか",
    es: "¿Cuántos años tienes?", de: "Wie alt bist du? — Ich bin acht." },
  { grade: 3, text: "___ is this? — It's a pen.", answer: "What",
    options: ["What", "Who", "Where", "When"], ja: "これは何ですか",
    es: "¿Qué es esto?", de: "Was ist das? — Das ist ein Stift." },
  { grade: 3, text: "___ this a cat? — Yes, it is.", answer: "Is",
    options: ["Is", "Are", "Am", "Do"], ja: "これはねこですか",
    es: "¿Esto es un gato?", de: "Ist das eine Katze? — Ja." },
  { grade: 3, text: "I ___ a dog.", answer: "have",
    options: ["have", "has", "having", "haves"], ja: "わたしは犬をかっています",
    es: "Tengo un perro", de: "Ich habe einen Hund." },
  { grade: 3, text: "___ color do you like? — I like blue.", answer: "What",
    options: ["What", "Who", "How", "Why"], ja: "何色がすきですか",
    es: "¿Qué color te gusta?", de: "Welche Farbe magst du? — Ich mag Blau." },
  { grade: 3, text: "I like ___. They are sweet.", answer: "apples",
    options: ["apples", "apple's", "appling", "appled"], ja: "わたしはりんごがすきです",
    es: "Me gustan las manzanas", de: "Ich mag Äpfel. Sie sind süß." },
  { grade: 3, text: "Do you like milk? — Yes, I ___.", answer: "do",
    options: ["do", "am", "is", "does"], ja: "はい、すきです",
    es: "Sí, me gusta", de: "Magst du Milch? — Ja." },
  { grade: 3, text: "___ is a book on the desk.", answer: "There",
    options: ["There", "Their", "They", "These"], ja: "つくえの上に本があります",
    es: "Hay un libro encima del pupitre", de: "Auf dem Tisch liegt ein Buch." },
  { grade: 3, text: "Please ___ down.", answer: "sit",
    options: ["sit", "set", "seat", "site"], ja: "すわってください",
    es: "Siéntate, por favor", de: "Setz dich bitte hin." },
  { grade: 3, text: "___ up, please.", answer: "Stand",
    options: ["Stand", "Sand", "Send", "Spend"], ja: "立ってください",
    es: "Levántate, por favor", de: "Steh bitte auf." },
  { grade: 3, text: "___ me, please.", answer: "Help",
    options: ["Help", "Hold", "Hope", "Heap"], ja: "手伝ってください",
    es: "Ayúdame, por favor", de: "Hilf mir bitte." },
  { grade: 3, text: "Open your ___, please.", answer: "book",
    options: ["book", "cook", "look", "took"], ja: "本を開いてください",
    es: "Abre el libro, por favor", de: "Schlag bitte dein Buch auf." },
  { grade: 3, text: "How many ___ do you have? — Three.", answer: "pens",
    options: ["pens", "pen", "pen's", "pening"], ja: "ペンを何本もっていますか",
    es: "¿Cuántos bolígrafos tienes?", de: "Wie viele Stifte hast du? — Drei." },
  { grade: 3, text: "It's a ___ day today.", answer: "sunny",
    options: ["sunny", "sun", "suns", "sunning"], ja: "今日は晴れです",
    es: "Hoy hace sol", de: "Heute ist ein sonniger Tag." },
  { grade: 3, text: "___ is the weather? — It's rainy.", answer: "How",
    options: ["How", "What", "Who", "Where"], ja: "天気はどうですか",
    es: "¿Qué tiempo hace?", de: "Wie ist das Wetter? — Es regnet." },
  { grade: 3, text: "I'm ___ Japan.", answer: "from",
    options: ["from", "for", "at", "of"], ja: "わたしは日本の出身です",
    es: "Soy de Japón", de: "Ich komme aus Japan." },
  { grade: 3, text: "___ name is Ken.", answer: "His",
    options: ["His", "He", "Him", "He's"], ja: "彼の名前はケンです",
    es: "Él se llama Ken", de: "Er heißt Ken." },
  { grade: 3, text: "This is ___ pencil.", answer: "my",
    options: ["my", "me", "I", "mine"], ja: "これはわたしのえんぴつです",
    es: "Este es mi lápiz", de: "Das ist mein Bleistift." },
  { grade: 3, text: "___ you ready? — Yes, I am.", answer: "Are",
    options: ["Are", "Is", "Do", "Am"], ja: "じゅんびはいいですか",
    es: "¿Estás listo?", de: "Bist du bereit? — Ja." },
  { grade: 3, text: "Let's ___ together.", answer: "sing",
    options: ["sing", "sings", "sang", "singing"], ja: "いっしょに歌おう",
    es: "Vamos a cantar juntos", de: "Lass uns zusammen singen." },
  { grade: 3, text: "I ___ soccer every day.", answer: "play",
    options: ["play", "plays", "played", "playing"], ja: "わたしは毎日サッカーをします",
    es: "Juego al fútbol todos los días", de: "Ich spiele jeden Tag Fußball." },
  { grade: 3, text: "___ me, where is the station?", answer: "Excuse",
    options: ["Excuse", "Exit", "Expect", "Explain"], ja: "すみません、駅はどこですか",
    es: "Perdona, ¿dónde está la estación?", de: "Entschuldigung, wo ist der Bahnhof?" },
  { grade: 3, text: "Happy ___! — Thank you.", answer: "birthday",
    options: ["birthday", "birdday", "borrowday", "bathday"], ja: "たんじょう日おめでとう",
    es: "¡Feliz cumpleaños!", de: "Alles Gute zum Geburtstag! — Danke." },
  { grade: 3, text: "___ is my friend, Yuki.", answer: "This",
    options: ["This", "These", "Those", "Them"], ja: "こちらは友だちのユキです",
    es: "Esta es mi amiga Yuki", de: "Das ist meine Freundin Yuki." },
  { grade: 3, text: "I ___ hungry.", answer: "am",
    options: ["am", "is", "are", "be"], ja: "わたしはおなかがすいています",
    es: "Tengo hambre", de: "Ich habe Hunger." },
  { grade: 3, text: "The cat is ___ the box.", answer: "in",
    options: ["in", "if", "is", "it"], ja: "ねこは箱の中にいます",
    es: "El gato está dentro de la caja", de: "Die Katze ist in der Kiste." },
  { grade: 3, text: "Look ___ the blackboard, please.", answer: "at",
    options: ["at", "of", "to", "by"], ja: "黒板を見てください",
    es: "Mira la pizarra, por favor", de: "Schau bitte auf die Tafel." },
  { grade: 3, text: "___ you speak Japanese? — Yes, a little.", answer: "Can",
    options: ["Can", "Are", "Is", "Am"], ja: "日本語を話せますか",
    es: "¿Hablas japonés?", de: "Kannst du Japanisch sprechen? — Ja, ein bisschen." },
  { grade: 4, text: "___ is that girl? — She's my sister.", answer: "Who",
    options: ["Who", "What", "Where", "How"], ja: "あの女の子はだれですか",
    es: "¿Quién es esa niña?", de: "Wer ist das Mädchen? — Das ist meine Schwester." },
  { grade: 4, text: "I ___ to school by bike.", answer: "go",
    options: ["go", "goes", "going", "went"], ja: "自転車で学校に行きます",
    es: "Voy al colegio en bici", de: "Ich fahre mit dem Fahrrad zur Schule." },
  { grade: 4, text: "___ do you get up? — At six thirty.", answer: "When",
    options: ["When", "Where", "Who", "Which"], ja: "いつ起きますか",
    es: "¿Cuándo te levantas?", de: "Wann stehst du auf? — Um halb sieben." },
  { grade: 4, text: "___ one do you want, red or blue?", answer: "Which",
    options: ["Which", "What", "Who", "Whose"], ja: "どちらがほしいですか",
    es: "¿Cuál quieres, el rojo o el azul?", de: "Welches möchtest du, das rote oder das blaue?" },
  { grade: 4, text: "___ bag is this? — It's mine.", answer: "Whose",
    options: ["Whose", "Who", "Which", "What"], ja: "これはだれのかばんですか",
    es: "¿De quién es esta bolsa?", de: "Wessen Tasche ist das? — Das ist meine." },
  { grade: 4, text: "I go to school ___ Monday.", answer: "on",
    options: ["on", "in", "at", "of"], ja: "月曜日に学校へ行きます",
    es: "Voy al colegio los lunes", de: "Ich gehe montags zur Schule." },
  { grade: 4, text: "My birthday is ___ July.", answer: "in",
    options: ["in", "on", "at", "to"], ja: "たんじょう日は7月です",
    es: "Mi cumpleaños es en julio", de: "Mein Geburtstag ist im Juli." },
  { grade: 4, text: "School starts ___ eight thirty.", answer: "at",
    options: ["at", "in", "on", "for"], ja: "学校は8時半に始まります",
    es: "Las clases empiezan a las ocho y media", de: "Die Schule beginnt um halb neun." },
  { grade: 4, text: "I ___ tennis after school.", answer: "play",
    options: ["play", "plays", "played", "playing"], ja: "放課後テニスをします",
    es: "Juego al tenis después de clase", de: "Ich spiele nach der Schule Tennis." },
  { grade: 4, text: "She ___ to music every night.", answer: "listens",
    options: ["listens", "listen", "listening", "listened"], ja: "彼女は毎晩音楽を聞きます",
    es: "Ella escucha música todas las noches", de: "Sie hört jeden Abend Musik." },
  { grade: 4, text: "He ___ have a bike.", answer: "doesn't",
    options: ["doesn't", "don't", "isn't", "aren't"], ja: "彼は自転車をもっていません",
    es: "Él no tiene bici", de: "Er hat kein Fahrrad." },
  { grade: 4, text: "___ she like cats? — Yes, she does.", answer: "Does",
    options: ["Does", "Do", "Is", "Are"], ja: "彼女はねこがすきですか",
    es: "¿A ella le gustan los gatos?", de: "Mag sie Katzen? — Ja." },
  { grade: 4, text: "I can ___ the piano.", answer: "play",
    options: ["play", "plays", "played", "playing"], ja: "わたしはピアノをひけます",
    es: "Sé tocar el piano", de: "Ich kann Klavier spielen." },
  { grade: 4, text: "I ___ swim well.", answer: "can't",
    options: ["can't", "don't", "isn't", "am not"], ja: "わたしはうまく泳げません",
    es: "No sé nadar bien", de: "Ich kann nicht gut schwimmen." },
  { grade: 4, text: "___ I use your pen? — Sure.", answer: "Can",
    options: ["Can", "Am", "Is", "Do"], ja: "ペンを使ってもいいですか",
    es: "¿Puedo usar tu bolígrafo?", de: "Kann ich deinen Stift benutzen? — Klar." },
  { grade: 4, text: "How ___ is this cap? — Five dollars.", answer: "much",
    options: ["much", "many", "long", "old"], ja: "このぼうしはいくらですか",
    es: "¿Cuánto cuesta esta gorra?", de: "Wie viel kostet diese Mütze? — Fünf Dollar." },
  { grade: 4, text: "How ___ students are there? — Twenty.", answer: "many",
    options: ["many", "much", "long", "far"], ja: "生徒は何人いますか",
    es: "¿Cuántos alumnos hay?", de: "Wie viele Schüler gibt es? — Zwanzig." },
  { grade: 4, text: "There ___ two dogs in the park.", answer: "are",
    options: ["are", "is", "am", "be"], ja: "公園に犬が2ひきいます",
    es: "Hay dos perros en el parque", de: "Im Park sind zwei Hunde." },
  { grade: 4, text: "The ball is ___ the desk.", answer: "under",
    options: ["under", "over", "into", "onto"], ja: "ボールはつくえの下にあります",
    es: "La pelota está debajo del pupitre", de: "Der Ball liegt unter dem Tisch." },
  { grade: 4, text: "My house is ___ to the school.", answer: "next",
    options: ["next", "near by", "far", "beside of"], ja: "わたしの家は学校のとなりです",
    es: "Mi casa está al lado del colegio", de: "Mein Haus ist direkt neben der Schule." },
  { grade: 4, text: "Turn ___ at the corner.", answer: "right",
    options: ["right", "write", "rice", "ride"], ja: "角を右に曲がってください",
    es: "Gira a la derecha en la esquina", de: "Bieg an der Ecke rechts ab." },
  { grade: 4, text: "Go ___ this street.", answer: "along",
    options: ["along", "alone", "aloud", "already"], ja: "この道にそって進んでください",
    es: "Sigue por esta calle", de: "Geh diese Straße entlang." },
  { grade: 4, text: "___ the third floor, please.", answer: "To",
    options: ["To", "At", "In", "On"], ja: "3階までお願いします",
    es: "A la tercera planta, por favor", de: "In den dritten Stock, bitte." },
  { grade: 4, text: "What ___ do you like? — I like summer.", answer: "season",
    options: ["season", "reason", "season's", "seasons'"], ja: "どの季節がすきですか",
    es: "¿Qué estación te gusta?", de: "Welche Jahreszeit magst du? — Ich mag den Sommer." },
  { grade: 4, text: "What ___ is it today? — It's Friday.", answer: "day",
    options: ["day", "date", "time", "week"], ja: "今日は何曜日ですか",
    es: "¿Qué día es hoy?", de: "Welcher Tag ist heute? — Heute ist Freitag." },
  { grade: 4, text: "I want ___ apple, please.", answer: "an",
    options: ["an", "a", "the", "of"], ja: "りんごを1つください",
    es: "Quiero una manzana, por favor", de: "Ich möchte bitte einen Apfel." },
  { grade: 4, text: "I have ___ homework today.", answer: "some",
    options: ["some", "many", "a few", "few"], ja: "今日は宿題があります",
    es: "Hoy tengo deberes", de: "Ich habe heute Hausaufgaben." },
  { grade: 4, text: "___ are my shoes.", answer: "These",
    options: ["These", "This", "That", "It"], ja: "これらはわたしのくつです",
    es: "Estos son mis zapatos", de: "Das sind meine Schuhe." },
  { grade: 4, text: "Don't ___ in the library.", answer: "run",
    options: ["run", "runs", "ran", "running"], ja: "図書館では走らないで",
    es: "No corras en la biblioteca", de: "Renn nicht in der Bibliothek." },
  { grade: 4, text: "Let's ___ lunch together.", answer: "have",
    options: ["have", "has", "had", "having"], ja: "いっしょにお昼を食べよう",
    es: "Vamos a comer juntos", de: "Lass uns zusammen zu Mittag essen." },
  { grade: 4, text: "I like dogs ___ cats.", answer: "and",
    options: ["and", "but", "or", "so"], ja: "犬もねこもすきです",
    es: "Me gustan los perros y los gatos", de: "Ich mag Hunde und Katzen." },
  { grade: 4, text: "I like tea, ___ I don't like coffee.", answer: "but",
    options: ["but", "and", "so", "if"], ja: "お茶はすきですが、コーヒーはすきではありません",
    es: "Me gusta el té, pero no me gusta el café", de: "Ich mag Tee, aber ich mag keinen Kaffee." },
  { grade: 4, text: "It's cold, ___ close the window.", answer: "so",
    options: ["so", "but", "or", "if"], ja: "寒いので、窓を閉めましょう",
    es: "Hace frío, así que cierra la ventana", de: "Es ist kalt, also mach das Fenster zu." },
  { grade: 4, text: "She is ___ TV now.", answer: "watching",
    options: ["watching", "watch", "watches", "watched"], ja: "彼女は今テレビを見ています",
    es: "Ella está viendo la tele ahora", de: "Sie schaut gerade fern." },
  { grade: 4, text: "They ___ playing in the yard.", answer: "are",
    options: ["are", "is", "am", "be"], ja: "彼らは庭で遊んでいます",
    es: "Ellos están jugando en el patio", de: "Sie spielen im Garten." },
  { grade: 4, text: "___ you help me? — Sure.", answer: "Can",
    options: ["Can", "Are", "Do you can", "Is"], ja: "手伝ってくれますか",
    es: "¿Me puedes ayudar?", de: "Kannst du mir helfen? — Klar." },
  { grade: 4, text: "This is ___ book, not yours.", answer: "her",
    options: ["her", "she", "hers of", "she's"], ja: "これは彼女の本で、あなたのではありません",
    es: "Este es su libro, no el tuyo", de: "Das ist ihr Buch, nicht deins." },
  { grade: 4, text: "Where ___ your parents? — They're at home.", answer: "are",
    options: ["are", "is", "am", "be"], ja: "ご両親はどこですか",
    es: "¿Dónde están tus padres?", de: "Wo sind deine Eltern? — Sie sind zu Hause." },
  // ⚠️ もとは "What job do you want to be?" となり、英語として成り立っていなかった
  //    （2026-09-24 日次QAで発見）。文を作り直し、選択肢も「A doctor」と噛み合うのが
  //    job だけになるようにした（work は "What work do you want?" でも通ってしまう）
  { grade: 4, text: "What ___ do you want? — A doctor.", answer: "job",
    options: ["job", "color", "food", "place"], ja: "どんな仕事がしたいですか",
    es: "¿De qué quieres trabajar?", de: "Was möchtest du werden? — Arzt." },
  { grade: 5, text: "I ___ to Kyoto last year.", answer: "went",
    options: ["went", "go", "goes", "going"], ja: "去年京都に行きました",
    es: "El año pasado fui a Kioto", de: "Letztes Jahr bin ich nach Kyoto gefahren." },
  { grade: 5, text: "I ___ soccer yesterday.", answer: "played",
    options: ["played", "play", "plays", "playing"], ja: "きのうサッカーをしました",
    es: "Ayer jugué al fútbol", de: "Gestern habe ich Fußball gespielt." },
  // is を外した。文中に時をしめす語が無く、"It is fun." も正しい文になっていた
  { grade: 5, text: "It ___ fun.", answer: "was",
    options: ["was", "were", "be", "been"], ja: "楽しかったです",
    es: "Fue divertido", de: "Es war lustig." },
  // are を外した。"We are happy to see you." も正しい文になっていた
  { grade: 5, text: "We ___ happy to see you.", answer: "were",
    options: ["were", "was", "be", "been"], ja: "あなたに会えてうれしかったです",
    es: "Nos alegramos de verte", de: "Wir haben uns gefreut, dich zu sehen." },
  { grade: 5, text: "I ___ eat natto, but now I like it.", answer: "didn't",
    options: ["didn't", "don't", "wasn't", "haven't"], ja: "昔は納豆を食べませんでしたが、今はすきです",
    es: "Antes no comía natto, pero ahora me gusta", de: "Früher habe ich kein Natto gegessen, aber jetzt mag ich es." },
  { grade: 5, text: "I'm going ___ study English tonight.", answer: "to",
    options: ["to", "for", "at", "of"], ja: "今夜英語を勉強するつもりです",
    es: "Esta noche voy a estudiar inglés", de: "Heute Abend werde ich Englisch lernen." },
  { grade: 5, text: "I ___ like some water, please.", answer: "would",
    options: ["would", "will", "am", "do"], ja: "お水をいただけますか",
    es: "Querría un poco de agua, por favor", de: "Ich hätte gern etwas Wasser, bitte." },
  { grade: 5, text: "This cake is ___ than that one.", answer: "sweeter",
    options: ["sweeter", "sweet", "sweetest", "more sweet"], ja: "このケーキはあれよりあまいです",
    es: "Este pastel es más dulce que aquel", de: "Dieser Kuchen ist süßer als jener." },
  { grade: 5, text: "Ken runs ___ fast as Yuki.", answer: "as",
    options: ["as", "so", "too", "very"], ja: "ケンはユキと同じくらい速く走ります",
    es: "Ken corre tan rápido como Yuki", de: "Ken läuft genauso schnell wie Yuki." },
  { grade: 5, text: "I like winter ___ I can ski.", answer: "because",
    options: ["because", "but", "or", "so that"], ja: "スキーができるので冬がすきです",
    es: "Me gusta el invierno porque puedo esquiar", de: "Ich mag den Winter, weil ich Ski fahren kann." },
  { grade: 5, text: "I visited my grandmother ___ Sunday.", answer: "last",
    options: ["last", "next", "this coming", "tomorrow"], ja: "先週の日曜日に祖母をたずねました",
    es: "El domingo pasado visité a mi abuela", de: "Letzten Sonntag habe ich meine Großmutter besucht." },
  { grade: 5, text: "My birthday is the ___ of May.", answer: "third",
    options: ["third", "three", "threeth", "thirdth"], ja: "たんじょう日は5月3日です",
    es: "Mi cumpleaños es el tres de mayo", de: "Mein Geburtstag ist am dritten Mai." },
  { grade: 5, text: "I want to visit Australia ___ I like animals.", answer: "because",
    options: ["because", "but", "though", "until"], ja: "動物がすきなのでオーストラリアに行きたいです",
    es: "Quiero visitar Australia porque me gustan los animales", de: "Ich möchte Australien besuchen, weil ich Tiere mag." },
  { grade: 5, text: "She is good ___ cooking.", answer: "at",
    options: ["at", "in", "on", "of"], ja: "彼女は料理が得意です",
    es: "A ella se le da bien cocinar", de: "Sie kann gut kochen." },
  { grade: 5, text: "How ___ is the tower? — About 300 meters.", answer: "tall",
    options: ["tall", "long", "much", "many"], ja: "そのタワーはどのくらいの高さですか",
    es: "¿Qué altura tiene la torre?", de: "Wie hoch ist der Turm? — Ungefähr 300 Meter." },
  { grade: 5, text: "___ you like some tea? — Yes, please.", answer: "Would",
    options: ["Would", "Are", "Do", "Can"], ja: "お茶はいかがですか",
    es: "¿Le apetece un té?", de: "Möchtest du etwas Tee? — Ja, gerne." },
  { grade: 5, text: "I'd like to ___ a table for two.", answer: "book",
    options: ["book", "take", "make up", "put"], ja: "2名で席を予約したいです",
    es: "Querría reservar una mesa para dos", de: "Ich möchte einen Tisch für zwei reservieren." },
  { grade: 5, text: "Can you tell me ___ to get to the museum?", answer: "how",
    options: ["how", "what", "who", "which"], ja: "博物館への行き方を教えてもらえますか",
    es: "¿Me puedes decir cómo llegar al museo?", de: "Kannst du mir sagen, wie ich zum Museum komme?" },
  { grade: 5, text: "I enjoyed ___ with my friends.", answer: "talking",
    options: ["talking", "talk", "talked", "to talk"], ja: "友だちと話すのを楽しみました",
    es: "Disfruté hablando con mis amigos", de: "Ich habe es genossen, mit meinen Freunden zu reden." },
  { grade: 5, text: "My dream is to ___ a vet.", answer: "become",
    options: ["become", "becomes", "becoming", "became"], ja: "わたしの夢はじゅう医になることです",
    es: "Mi sueño es ser veterinario", de: "Mein Traum ist, Tierarzt zu werden." },
  // are を外した。"There are many people..." も数が合っていて正しい文になっていた
  { grade: 5, text: "There ___ many people at the festival.", answer: "were",
    options: ["were", "was", "be", "been"], ja: "祭りにはたくさんの人がいました",
    es: "Había mucha gente en la fiesta", de: "Beim Fest waren viele Leute." },
  { grade: 6, text: "This is the ___ movie I have ever seen.", answer: "best",
    options: ["best", "good", "better", "more good"], ja: "これは今まで見た中でいちばんよい映画です",
    es: "Esta es la mejor película que he visto nunca", de: "Das ist der beste Film, den ich je gesehen habe." },
  { grade: 6, text: "Mt. Fuji is the ___ mountain in Japan.", answer: "highest",
    options: ["highest", "high", "higher", "more high"], ja: "富士山は日本でいちばん高い山です",
    es: "El monte Fuji es la montaña más alta de Japón", de: "Der Fuji ist der höchste Berg Japans." },
  { grade: 6, text: "I have ___ been to Okinawa.", answer: "never",
    options: ["never", "ever", "yet", "already"], ja: "沖縄には行ったことがありません",
    es: "Nunca he estado en Okinawa", de: "Ich war noch nie in Okinawa." },
  { grade: 6, text: "Have you ___ finished your homework? — Yes, I have.", answer: "already",
    options: ["already", "yet", "never", "ago"], ja: "もう宿題を終えましたか",
    es: "¿Ya has terminado los deberes?", de: "Hast du deine Hausaufgaben schon fertig gemacht? — Ja." },
  { grade: 6, text: "I ___ studying English for three years.", answer: "have been",
    options: ["have been", "am", "was", "had"], ja: "3年間英語を勉強しています",
    es: "Llevo tres años estudiando inglés", de: "Ich lerne seit drei Jahren Englisch." },
  { grade: 6, text: "The letter ___ written by my father.", answer: "was",
    options: ["was", "did", "has", "were"], ja: "その手紙は父によって書かれました",
    es: "La carta fue escrita por mi padre", de: "Der Brief wurde von meinem Vater geschrieben." },
  { grade: 6, text: "English is ___ in many countries.", answer: "spoken",
    options: ["spoken", "speak", "speaking", "spoke"], ja: "英語は多くの国で話されています",
    es: "El inglés se habla en muchos países", de: "Englisch wird in vielen Ländern gesprochen." },
  { grade: 6, text: "If you ___ hard, you will pass the test.", answer: "study",
    options: ["study", "studies", "studied", "studying"], ja: "一生けんめい勉強すれば、テストに合格するでしょう",
    es: "Si estudias mucho, aprobarás el examen", de: "Wenn du fleißig lernst, wirst du die Prüfung bestehen." },
  { grade: 6, text: "I think ___ this book is interesting.", answer: "that",
    options: ["that", "what", "which", "who"], ja: "この本はおもしろいと思います",
    es: "Creo que este libro es interesante", de: "Ich finde, dass dieses Buch interessant ist." },
  { grade: 6, text: "The boy ___ is running is my brother.", answer: "who",
    options: ["who", "which", "whose", "whom"], ja: "走っている男の子はわたしの兄弟です",
    es: "El niño que está corriendo es mi hermano", de: "Der Junge, der da rennt, ist mein Bruder." },
  { grade: 6, text: "I want to be a teacher ___ help children.", answer: "to",
    options: ["to", "for", "so", "that"], ja: "子どもを助けるために先生になりたいです",
    es: "Quiero ser profesor para ayudar a los niños", de: "Ich möchte Lehrer werden, um Kindern zu helfen." },
  { grade: 6, text: "It is important ___ read books.", answer: "to",
    options: ["to", "for", "of", "at"], ja: "本を読むことは大切です",
    es: "Es importante leer libros", de: "Es ist wichtig, Bücher zu lesen." },
  { grade: 6, text: "I'm looking forward ___ seeing you.", answer: "to",
    options: ["to", "for", "at", "on"], ja: "お会いするのを楽しみにしています",
    es: "Tengo muchas ganas de verte", de: "Ich freue mich darauf, dich zu sehen." },
  { grade: 6, text: "She asked me ___ I liked sushi.", answer: "if",
    options: ["if", "that", "so", "or"], ja: "彼女はわたしにすしがすきかたずねました",
    es: "Ella me preguntó si me gustaba el sushi", de: "Sie fragte mich, ob ich Sushi mag." },
  { grade: 6, text: "My town is famous ___ its old temple.", answer: "for",
    options: ["for", "of", "at", "with"], ja: "わたしの町は古い寺で有名です",
    es: "Mi pueblo es famoso por su templo antiguo", de: "Meine Stadt ist für ihren alten Tempel bekannt." },
  { grade: 6, text: "We should ___ care of the environment.", answer: "take",
    options: ["take", "make", "do", "give"], ja: "わたしたちは環境を大切にすべきです",
    es: "Deberíamos cuidar el medio ambiente", de: "Wir sollten auf die Umwelt achten." },
  { grade: 6, text: "You ___ not eat in the classroom.", answer: "must",
    options: ["must", "can", "will", "would"], ja: "教室で食べてはいけません",
    es: "No se puede comer en el aula", de: "Du darfst im Klassenzimmer nicht essen." },
  { grade: 6, text: "I ___ to finish this report by Friday.", answer: "have",
    options: ["have", "must", "should", "can"], ja: "金曜日までにこの報告を終えなければなりません",
    es: "Tengo que terminar este informe antes del viernes", de: "Ich muss diesen Bericht bis Freitag fertig machen." },
  { grade: 6, text: "Could you ___ that again, please?", answer: "say",
    options: ["say", "tell", "speak", "talk"], ja: "もう一度言っていただけますか",
    es: "¿Podría repetirlo, por favor?", de: "Könntest du das bitte noch einmal sagen?" },
  { grade: 6, text: "___ don't we go to the beach?", answer: "Why",
    options: ["Why", "How", "What", "When"], ja: "海に行きませんか",
    es: "¿Por qué no vamos a la playa?", de: "Wollen wir nicht an den Strand gehen?" },
  { grade: 6, text: "I was ___ when I heard the news.", answer: "surprised",
    options: ["surprised", "surprising", "surprise", "surprises"], ja: "その知らせを聞いておどろきました",
    es: "Me sorprendí cuando escuché la noticia", de: "Ich war überrascht, als ich die Nachricht hörte." },
  { grade: 6, text: "Kyoto is worth ___.", answer: "visiting",
    options: ["visiting", "visit", "to visit", "visited"], ja: "京都はたずねる価値があります",
    es: "Kioto merece la pena visitarlo", de: "Kyoto ist einen Besuch wert." },
];
