// ===== 英語（外国語）のコンテンツ =====
// 日本の小学生向け。学習指導要領では3・4年で外国語活動、5・6年で教科としての外国語。
// そのため grade 3 から出題し、3・4年は身近な単語中心、5・6年で文や表現を扱う。
//
// word: 英語 / grade: 出題を始める学年
// ja / es: 学習者の母語ラベル。表示言語に合わせて buildEnglishPool() が選ぶ。
//
// ⚠️ **問題本体は英語側（word / text / answer / options）で、母語ラベルは訳にすぎない。**
//    だから ja の隣に es を置くだけで、このバンクはそのままスペイン語話者向けの
//    英語教材になる（es-handoff.md §2）。語を足すときは ja と es を必ず両方書くこと。
//    片方だけだと t() と同じで日本語が静かに混ざる。`node tools/check_i18n_keys.js` が検出する。
//
// ⚠️ EN_WORDS の母語ラベルは、そのまま4択の選択肢になる（他の語のラベルが誤答に回る）。
//    **同じ訳語を2語に付けないこと。** 正解が2つある問題になる。

const EN_WORDS = [
  // 3年：身のまわりのもの・色・数
  { grade: 3, word: "apple", ja: "りんご", es: "manzana" },
  { grade: 3, word: "dog", ja: "いぬ", es: "perro" },
  { grade: 3, word: "cat", ja: "ねこ", es: "gato" },
  { grade: 3, word: "book", ja: "ほん", es: "libro" },
  { grade: 3, word: "red", ja: "あか", es: "rojo" },
  { grade: 3, word: "blue", ja: "あお", es: "azul" },
  { grade: 3, word: "green", ja: "みどり", es: "verde" },
  { grade: 3, word: "yellow", ja: "きいろ", es: "amarillo" },
  { grade: 3, word: "one", ja: "1", es: "uno" },
  { grade: 3, word: "two", ja: "2", es: "dos" },
  { grade: 3, word: "three", ja: "3", es: "tres" },
  { grade: 3, word: "school", ja: "がっこう", es: "colegio" },
  { grade: 3, word: "pencil", ja: "えんぴつ", es: "lápiz" },
  { grade: 3, word: "bag", ja: "かばん", es: "bolsa" },
  { grade: 3, word: "water", ja: "みず", es: "agua" },
  { grade: 3, word: "fish", ja: "さかな", es: "pez" },
  { grade: 3, word: "bird", ja: "とり", es: "pájaro" },
  { grade: 3, word: "tree", ja: "き", es: "árbol" },
  { grade: 3, word: "sun", ja: "たいよう", es: "sol" },
  { grade: 3, word: "rain", ja: "あめ", es: "lluvia" },

  // 4年：曜日・食べ物・動作
  { grade: 4, word: "Monday", ja: "月よう日", es: "lunes" },
  { grade: 4, word: "Sunday", ja: "日よう日", es: "domingo" },
  { grade: 4, word: "breakfast", ja: "朝ごはん", es: "desayuno" },
  { grade: 4, word: "lunch", ja: "昼ごはん", es: "comida del mediodía" },
  { grade: 4, word: "dinner", ja: "夕ごはん", es: "cena" },
  { grade: 4, word: "run", ja: "走る", es: "correr" },
  { grade: 4, word: "swim", ja: "泳ぐ", es: "nadar" },
  { grade: 4, word: "read", ja: "読む", es: "leer" },
  { grade: 4, word: "write", ja: "書く", es: "escribir" },
  { grade: 4, word: "eat", ja: "食べる", es: "comer" },
  { grade: 4, word: "spring", ja: "春", es: "primavera" },
  { grade: 4, word: "summer", ja: "夏", es: "verano" },
  { grade: 4, word: "autumn", ja: "秋", es: "otoño" },
  { grade: 4, word: "winter", ja: "冬", es: "invierno" },
  { grade: 4, word: "morning", ja: "朝", es: "mañana" },
  { grade: 4, word: "night", ja: "夜", es: "noche" },
  { grade: 4, word: "friend", ja: "友だち", es: "amigo" },
  { grade: 4, word: "family", ja: "家族", es: "familia" },
  { grade: 4, word: "teacher", ja: "先生", es: "profesor" },
  { grade: 4, word: "music", ja: "音楽", es: "música" },
  { grade: 4, word: "milk", ja: "ぎゅうにゅう", es: "leche" },
  { grade: 4, word: "rice", ja: "ごはん", es: "arroz" },
  { grade: 4, word: "egg", ja: "たまご", es: "huevo" },
  { grade: 4, word: "notebook", ja: "ノート", es: "cuaderno" },
  { grade: 4, word: "eraser", ja: "けしゴム", es: "goma de borrar" },
  { grade: 4, word: "jump", ja: "とぶ", es: "saltar" },
  { grade: 4, word: "sing", ja: "うたう", es: "cantar" },
  { grade: 4, word: "dance", ja: "おどる", es: "bailar" },
  { grade: 4, word: "cook", ja: "りょうりする", es: "cocinar" },
  { grade: 4, word: "sleep", ja: "ねる", es: "dormir" },

  // 5年：教科・場所・性質
  { grade: 5, word: "science", ja: "理科", es: "ciencias" },
  { grade: 5, word: "math", ja: "算数", es: "matemáticas" },
  { grade: 5, word: "hospital", ja: "病院", es: "hospital" },
  { grade: 5, word: "station", ja: "駅", es: "estación" },
  { grade: 5, word: "library", ja: "図書館", es: "biblioteca" },
  { grade: 5, word: "park", ja: "公園", es: "parque" },
  { grade: 5, word: "country", ja: "国", es: "país" },
  { grade: 5, word: "city", ja: "都市", es: "ciudad" },
  { grade: 5, word: "beautiful", ja: "美しい", es: "hermoso" },
  { grade: 5, word: "difficult", ja: "むずかしい", es: "difícil" },
  { grade: 5, word: "important", ja: "大切な", es: "importante" },
  { grade: 5, word: "delicious", ja: "おいしい", es: "delicioso" },
  { grade: 5, word: "favorite", ja: "お気に入りの", es: "favorito" },
  { grade: 5, word: "future", ja: "将来", es: "futuro" },
  { grade: 5, word: "dream", ja: "ゆめ", es: "sueño" },

  // 6年：抽象語・行事
  { grade: 6, word: "memory", ja: "思い出", es: "recuerdo" },
  { grade: 6, word: "experience", ja: "経験", es: "experiencia" },
  { grade: 6, word: "environment", ja: "環境", es: "medio ambiente" },
  { grade: 6, word: "culture", ja: "文化", es: "cultura" },
  { grade: 6, word: "peace", ja: "平和", es: "paz" },
  { grade: 6, word: "festival", ja: "祭り", es: "fiesta" },
  { grade: 6, word: "graduation", ja: "卒業", es: "graduación" },
  { grade: 6, word: "junior high school", ja: "中学校", es: "escuela secundaria" },
  { grade: 6, word: "volunteer", ja: "ボランティア", es: "voluntario" },
  { grade: 6, word: "president", ja: "大統領", es: "presidente" },
];

// あいさつ・やりとり。text の ___ が空所。
// ja / es は解説にだけ使う（選択肢は英語なので、訳語が重複しても問題は壊れない）。
const EN_PHRASES = [
  { grade: 3, text: "How are you? — I'm ___, thank you.", answer: "fine",
    options: ["fine", "eat", "book", "red"], ja: "げんきです、ありがとう",
    es: "Estoy bien, gracias" },
  { grade: 3, text: "___ morning!", answer: "Good",
    options: ["Good", "Many", "Very", "Some"], ja: "おはよう",
    es: "¡Buenos días!" },
  { grade: 3, text: "My ___ is Taro.", answer: "name",
    options: ["name", "color", "food", "book"], ja: "わたしの名前はタロウです",
    es: "Me llamo Taro" },
  { grade: 3, text: "Thank you. — You're ___.", answer: "welcome",
    options: ["welcome", "sorry", "happy", "ready"], ja: "どういたしまして",
    es: "De nada" },
  { grade: 4, text: "___ do you like? — I like soccer.", answer: "What",
    options: ["What", "Who", "Where", "When"], ja: "何がすきですか",
    es: "¿Qué te gusta?" },
  { grade: 4, text: "___ is your birthday? — It's in May.", answer: "When",
    options: ["When", "What", "Who", "How"], ja: "たんじょう日はいつですか",
    es: "¿Cuándo es tu cumpleaños?" },
  { grade: 4, text: "I ___ up at six.", answer: "get",
    options: ["get", "go", "make", "take"], ja: "6時に起きます",
    es: "Me levanto a las seis" },
  { grade: 4, text: "___ is the library? — It's near the park.", answer: "Where",
    options: ["Where", "What", "Why", "Who"], ja: "図書館はどこですか",
    es: "¿Dónde está la biblioteca?" },
  { grade: 5, text: "I want ___ be a teacher.", answer: "to",
    options: ["to", "of", "in", "at"], ja: "先生になりたいです",
    es: "Quiero ser profesor" },
  { grade: 5, text: "This is ___ favorite place.", answer: "my",
    options: ["my", "me", "I", "mine"], ja: "ここはわたしのお気に入りの場所です",
    es: "Este es mi lugar favorito" },
  { grade: 5, text: "He ___ soccer every Sunday.", answer: "plays",
    options: ["plays", "play", "playing", "played"], ja: "彼は毎週日よう日にサッカーをします",
    es: "Él juega al fútbol todos los domingos" },
  { grade: 5, text: "___ much is this? — It's 500 yen.", answer: "How",
    options: ["How", "What", "Who", "Where"], ja: "これはいくらですか",
    es: "¿Cuánto cuesta esto?" },
  { grade: 5, text: "Can you ___ me your pen?", answer: "lend",
    options: ["lend", "borrow", "buy", "give up"], ja: "ペンを貸してくれる？",
    es: "¿Me prestas tu bolígrafo?" },
  { grade: 5, text: "I usually ___ breakfast at seven.", answer: "have",
    options: ["have", "has", "having", "had"], ja: "たいてい7時に朝食を食べます",
    es: "Normalmente desayuno a las siete" },
  { grade: 5, text: "___ do you go to school? — By bus.", answer: "How",
    options: ["How", "What", "When", "Why"], ja: "どうやって学校に行きますか",
    es: "¿Cómo vas al colegio?" },
  { grade: 5, text: "She is good ___ playing the piano.", answer: "at",
    options: ["at", "in", "on", "for"], ja: "彼女はピアノをひくのが得意です",
    es: "A ella se le da bien tocar el piano" },
  { grade: 5, text: "There ___ two cats under the table.", answer: "are",
    options: ["are", "is", "am", "be"], ja: "テーブルの下にねこが2ひきいます",
    es: "Hay dos gatos debajo de la mesa" },
  { grade: 6, text: "I ___ to Kyoto last summer.", answer: "went",
    options: ["went", "go", "going", "goes"], ja: "去年の夏、京都に行きました",
    es: "El verano pasado fui a Kioto" },
  { grade: 6, text: "My best ___ is the school festival.", answer: "memory",
    options: ["memory", "morning", "market", "minute"], ja: "一番の思い出は学園祭です",
    es: "Mi mejor recuerdo es la fiesta del colegio" },
  { grade: 6, text: "I want to ___ the environment.", answer: "protect",
    options: ["protect", "produce", "prepare", "present"], ja: "環境を守りたいです",
    es: "Quiero proteger el medio ambiente" },
  { grade: 6, text: "We ___ enjoyed the trip.", answer: "all",
    options: ["all", "every", "each", "both"], ja: "わたしたちはみんな旅行を楽しみました",
    es: "Todos disfrutamos del viaje" },
  { grade: 6, text: "This book is ___ than that one.", answer: "more interesting",
    options: ["more interesting", "interesting", "most interesting", "interestinger"], ja: "この本はあの本より面白いです",
    es: "Este libro es más interesante que aquel" },
  { grade: 6, text: "If it ___ tomorrow, we will stay home.", answer: "rains",
    options: ["rains", "rain", "rained", "raining"], ja: "もし明日雨が降ったら、家にいます",
    es: "Si mañana llueve, nos quedaremos en casa" },
  { grade: 6, text: "I have ___ finished my homework.", answer: "already",
    options: ["already", "yet", "ever", "still"], ja: "もう宿題を終わらせました",
    es: "Ya he terminado los deberes" },
  { grade: 6, text: "This is the book ___ I read last week.", answer: "that",
    options: ["that", "who", "what", "where"], ja: "これは先週読んだ本です",
    es: "Este es el libro que leí la semana pasada" },
  { grade: 3, text: "Nice to ___ you.", answer: "meet",
    options: ["meet", "make", "read", "open"], ja: "はじめまして",
    es: "Encantado de conocerte" },
  { grade: 3, text: "___ you like apples? — Yes, I do.", answer: "Do",
    options: ["Do", "Is", "Are", "Am"], ja: "りんごはすきですか",
    es: "¿Te gustan las manzanas?" },
  { grade: 3, text: "See ___ tomorrow!", answer: "you",
    options: ["you", "me", "it", "we"], ja: "また明日",
    es: "¡Hasta mañana!" },
  { grade: 3, text: "Let's ___ soccer.", answer: "play",
    options: ["play", "eat", "read", "open"], ja: "サッカーをしよう",
    es: "Vamos a jugar al fútbol" },
  { grade: 3, text: "___ is this? — It's a cat.", answer: "What",
    options: ["What", "Who", "When", "Where"], ja: "これは何ですか",
    es: "¿Qué es esto?" },
  { grade: 3, text: "Here you ___.", answer: "are",
    options: ["are", "is", "am", "be"], ja: "はい、どうぞ",
    es: "Aquí tienes" },
  { grade: 4, text: "___ old are you? — I'm ten.", answer: "How",
    options: ["How", "What", "Who", "Why"], ja: "何さいですか",
    es: "¿Cuántos años tienes?" },
  { grade: 4, text: "I go to school ___ bike.", answer: "by",
    options: ["by", "in", "on", "to"], ja: "自転車で学校に行きます",
    es: "Voy al colegio en bici" },
  { grade: 4, text: "She ___ a red bag.", answer: "has",
    options: ["has", "have", "having", "is"], ja: "彼女は赤いかばんを持っています",
    es: "Ella tiene una bolsa roja" },
  { grade: 3, text: "I ___ a red pen.", answer: "have",
    options: ["have", "has", "is", "am"], ja: "赤いペンを持っています",
    es: "Tengo un bolígrafo rojo" },
  { grade: 3, text: "This ___ my dog.", answer: "is",
    options: ["is", "am", "are", "be"], ja: "これはわたしの犬です",
    es: "Este es mi perro" },
  { grade: 3, text: "I ___ blue.", answer: "like",
    options: ["like", "likes", "liking", "liked"], ja: "青がすきです",
    es: "Me gusta el azul" },
  { grade: 3, text: "___ birthday!", answer: "Happy",
    options: ["Happy", "Good", "Nice", "Great"], ja: "たんじょう日おめでとう",
    es: "¡Feliz cumpleaños!" },
  { grade: 3, text: "___ is the bag?", answer: "Where",
    options: ["Where", "What", "Who", "When"], ja: "かばんはどこですか",
    es: "¿Dónde está la bolsa?" },
  { grade: 3, text: "I ___ swim.", answer: "can",
    options: ["can", "do", "am", "is"], ja: "わたしは泳げます",
    es: "Sé nadar" },
  { grade: 4, text: "I ___ a new bike.", answer: "want",
    options: ["want", "wants", "wanting", "wanted"], ja: "新しい自転車がほしいです",
    es: "Quiero una bici nueva" },
  { grade: 4, text: "She ___ my sister.", answer: "is",
    options: ["is", "are", "am", "be"], ja: "彼女はわたしの姉（妹）です",
    es: "Ella es mi hermana" },
  { grade: 4, text: "I ___ like natto.", answer: "don't",
    options: ["don't", "isn't", "doesn't", "can't"], ja: "わたしは納豆がすきではありません",
    es: "No me gusta el natto" },
  { grade: 4, text: "___ go to the park.", answer: "Let's",
    options: ["Let's", "Let", "Lets", "Letting"], ja: "公園に行こう",
    es: "Vamos al parque" },
  { grade: 4, text: "He ___ run fast.", answer: "can",
    options: ["can", "cans", "canning", "could"], ja: "彼は速く走ることができます",
    es: "Él sabe correr rápido" },
  { grade: 4, text: "___ time is it?", answer: "What",
    options: ["What", "When", "Where", "Why"], ja: "何時ですか",
    es: "¿Qué hora es?" },
  { grade: 3, text: "___ afternoon!", answer: "Good",
    options: ["Good", "Nice", "Fine", "Well"], ja: "こんにちは（午後のあいさつ）",
    es: "¡Buenas tardes!" },
  { grade: 3, text: "Good ___! See you tomorrow.", answer: "night",
    options: ["night", "day", "time", "week"], ja: "おやすみなさい",
    es: "¡Buenas noches!" },
  { grade: 3, text: "___ you! — You're welcome.", answer: "Thank",
    options: ["Thank", "Think", "Take", "Talk"], ja: "ありがとう",
    es: "¡Gracias!" },
  { grade: 3, text: "I'm ___. — That's OK.", answer: "sorry",
    options: ["sorry", "sunny", "story", "start"], ja: "ごめんなさい",
    es: "Lo siento" },
  { grade: 3, text: "I am ___ now.", answer: "hungry",
    options: ["hungry", "hungrily", "hunger", "hungering"], ja: "わたしは今おなかがすいています",
    es: "Ahora tengo hambre" },
  { grade: 3, text: "___ you later!", answer: "See",
    options: ["See", "Sit", "Say", "Set"], ja: "またあとでね",
    es: "¡Hasta luego!" },
  { grade: 3, text: "How ___ you? — I'm eight.", answer: "old",
    options: ["old", "many", "long", "far"], ja: "何さいですか",
    es: "¿Cuántos años tienes?" },
  { grade: 3, text: "___ is this? — It's a pen.", answer: "What",
    options: ["What", "Who", "Where", "When"], ja: "これは何ですか",
    es: "¿Qué es esto?" },
  { grade: 3, text: "___ this a cat? — Yes, it is.", answer: "Is",
    options: ["Is", "Are", "Am", "Do"], ja: "これはねこですか",
    es: "¿Esto es un gato?" },
  { grade: 3, text: "I ___ a dog.", answer: "have",
    options: ["have", "has", "having", "haves"], ja: "わたしは犬をかっています",
    es: "Tengo un perro" },
  { grade: 3, text: "___ color do you like? — I like blue.", answer: "What",
    options: ["What", "Who", "How", "Why"], ja: "何色がすきですか",
    es: "¿Qué color te gusta?" },
  { grade: 3, text: "I like ___. They are sweet.", answer: "apples",
    options: ["apples", "apple's", "appling", "appled"], ja: "わたしはりんごがすきです",
    es: "Me gustan las manzanas" },
  { grade: 3, text: "Do you like milk? — Yes, I ___.", answer: "do",
    options: ["do", "am", "is", "does"], ja: "はい、すきです",
    es: "Sí, me gusta" },
  { grade: 3, text: "___ is a book on the desk.", answer: "There",
    options: ["There", "Their", "They", "These"], ja: "つくえの上に本があります",
    es: "Hay un libro encima del pupitre" },
  { grade: 3, text: "Please ___ down.", answer: "sit",
    options: ["sit", "set", "seat", "site"], ja: "すわってください",
    es: "Siéntate, por favor" },
  { grade: 3, text: "___ up, please.", answer: "Stand",
    options: ["Stand", "Sand", "Send", "Spend"], ja: "立ってください",
    es: "Levántate, por favor" },
  { grade: 3, text: "___ me, please.", answer: "Help",
    options: ["Help", "Hold", "Hope", "Heap"], ja: "手伝ってください",
    es: "Ayúdame, por favor" },
  { grade: 3, text: "Open your ___, please.", answer: "book",
    options: ["book", "cook", "look", "took"], ja: "本を開いてください",
    es: "Abre el libro, por favor" },
  { grade: 3, text: "How many ___ do you have? — Three.", answer: "pens",
    options: ["pens", "pen", "pen's", "pening"], ja: "ペンを何本もっていますか",
    es: "¿Cuántos bolígrafos tienes?" },
  { grade: 3, text: "It's a ___ day today.", answer: "sunny",
    options: ["sunny", "sun", "suns", "sunning"], ja: "今日は晴れです",
    es: "Hoy hace sol" },
  { grade: 3, text: "___ is the weather? — It's rainy.", answer: "How",
    options: ["How", "What", "Who", "Where"], ja: "天気はどうですか",
    es: "¿Qué tiempo hace?" },
  { grade: 3, text: "I'm ___ Japan.", answer: "from",
    options: ["from", "for", "at", "of"], ja: "わたしは日本の出身です",
    es: "Soy de Japón" },
  { grade: 3, text: "___ name is Ken.", answer: "His",
    options: ["His", "He", "Him", "He's"], ja: "彼の名前はケンです",
    es: "Él se llama Ken" },
  { grade: 3, text: "This is ___ pencil.", answer: "my",
    options: ["my", "me", "I", "mine"], ja: "これはわたしのえんぴつです",
    es: "Este es mi lápiz" },
  { grade: 3, text: "___ you ready? — Yes, I am.", answer: "Are",
    options: ["Are", "Is", "Do", "Am"], ja: "じゅんびはいいですか",
    es: "¿Estás listo?" },
  { grade: 3, text: "Let's ___ together.", answer: "sing",
    options: ["sing", "sings", "sang", "singing"], ja: "いっしょに歌おう",
    es: "Vamos a cantar juntos" },
  { grade: 3, text: "I ___ soccer every day.", answer: "play",
    options: ["play", "plays", "played", "playing"], ja: "わたしは毎日サッカーをします",
    es: "Juego al fútbol todos los días" },
  { grade: 3, text: "___ me, where is the station?", answer: "Excuse",
    options: ["Excuse", "Exit", "Expect", "Explain"], ja: "すみません、駅はどこですか",
    es: "Perdona, ¿dónde está la estación?" },
  { grade: 3, text: "Happy ___! — Thank you.", answer: "birthday",
    options: ["birthday", "birdday", "borrowday", "bathday"], ja: "たんじょう日おめでとう",
    es: "¡Feliz cumpleaños!" },
  { grade: 3, text: "___ is my friend, Yuki.", answer: "This",
    options: ["This", "These", "Those", "Them"], ja: "こちらは友だちのユキです",
    es: "Esta es mi amiga Yuki" },
  { grade: 3, text: "I ___ hungry.", answer: "am",
    options: ["am", "is", "are", "be"], ja: "わたしはおなかがすいています",
    es: "Tengo hambre" },
  { grade: 3, text: "The cat is ___ the box.", answer: "in",
    options: ["in", "if", "is", "it"], ja: "ねこは箱の中にいます",
    es: "El gato está dentro de la caja" },
  { grade: 3, text: "Look ___ the blackboard, please.", answer: "at",
    options: ["at", "of", "to", "by"], ja: "黒板を見てください",
    es: "Mira la pizarra, por favor" },
  { grade: 3, text: "___ you speak Japanese? — Yes, a little.", answer: "Can",
    options: ["Can", "Are", "Is", "Am"], ja: "日本語を話せますか",
    es: "¿Hablas japonés?" },
  { grade: 4, text: "___ is that girl? — She's my sister.", answer: "Who",
    options: ["Who", "What", "Where", "How"], ja: "あの女の子はだれですか",
    es: "¿Quién es esa niña?" },
  { grade: 4, text: "I ___ to school by bike.", answer: "go",
    options: ["go", "goes", "going", "went"], ja: "自転車で学校に行きます",
    es: "Voy al colegio en bici" },
  { grade: 4, text: "___ do you get up? — At six thirty.", answer: "When",
    options: ["When", "Where", "Who", "Which"], ja: "いつ起きますか",
    es: "¿Cuándo te levantas?" },
  { grade: 4, text: "___ one do you want, red or blue?", answer: "Which",
    options: ["Which", "What", "Who", "Whose"], ja: "どちらがほしいですか",
    es: "¿Cuál quieres, el rojo o el azul?" },
  { grade: 4, text: "___ bag is this? — It's mine.", answer: "Whose",
    options: ["Whose", "Who", "Which", "What"], ja: "これはだれのかばんですか",
    es: "¿De quién es esta bolsa?" },
  { grade: 4, text: "I go to school ___ Monday.", answer: "on",
    options: ["on", "in", "at", "of"], ja: "月曜日に学校へ行きます",
    es: "Voy al colegio los lunes" },
  { grade: 4, text: "My birthday is ___ July.", answer: "in",
    options: ["in", "on", "at", "to"], ja: "たんじょう日は7月です",
    es: "Mi cumpleaños es en julio" },
  { grade: 4, text: "School starts ___ eight thirty.", answer: "at",
    options: ["at", "in", "on", "for"], ja: "学校は8時半に始まります",
    es: "Las clases empiezan a las ocho y media" },
  { grade: 4, text: "I ___ tennis after school.", answer: "play",
    options: ["play", "plays", "played", "playing"], ja: "放課後テニスをします",
    es: "Juego al tenis después de clase" },
  { grade: 4, text: "She ___ to music every night.", answer: "listens",
    options: ["listens", "listen", "listening", "listened"], ja: "彼女は毎晩音楽を聞きます",
    es: "Ella escucha música todas las noches" },
  { grade: 4, text: "He ___ have a bike.", answer: "doesn't",
    options: ["doesn't", "don't", "isn't", "aren't"], ja: "彼は自転車をもっていません",
    es: "Él no tiene bici" },
  { grade: 4, text: "___ she like cats? — Yes, she does.", answer: "Does",
    options: ["Does", "Do", "Is", "Are"], ja: "彼女はねこがすきですか",
    es: "¿A ella le gustan los gatos?" },
  { grade: 4, text: "I can ___ the piano.", answer: "play",
    options: ["play", "plays", "played", "playing"], ja: "わたしはピアノをひけます",
    es: "Sé tocar el piano" },
  { grade: 4, text: "I ___ swim well.", answer: "can't",
    options: ["can't", "don't", "isn't", "am not"], ja: "わたしはうまく泳げません",
    es: "No sé nadar bien" },
  { grade: 4, text: "___ I use your pen? — Sure.", answer: "Can",
    options: ["Can", "Am", "Is", "Do"], ja: "ペンを使ってもいいですか",
    es: "¿Puedo usar tu bolígrafo?" },
  { grade: 4, text: "How ___ is this cap? — Five dollars.", answer: "much",
    options: ["much", "many", "long", "old"], ja: "このぼうしはいくらですか",
    es: "¿Cuánto cuesta esta gorra?" },
  { grade: 4, text: "How ___ students are there? — Twenty.", answer: "many",
    options: ["many", "much", "long", "far"], ja: "生徒は何人いますか",
    es: "¿Cuántos alumnos hay?" },
  { grade: 4, text: "There ___ two dogs in the park.", answer: "are",
    options: ["are", "is", "am", "be"], ja: "公園に犬が2ひきいます",
    es: "Hay dos perros en el parque" },
  { grade: 4, text: "The ball is ___ the desk.", answer: "under",
    options: ["under", "over", "into", "onto"], ja: "ボールはつくえの下にあります",
    es: "La pelota está debajo del pupitre" },
  { grade: 4, text: "My house is ___ to the school.", answer: "next",
    options: ["next", "near by", "far", "beside of"], ja: "わたしの家は学校のとなりです",
    es: "Mi casa está al lado del colegio" },
  { grade: 4, text: "Turn ___ at the corner.", answer: "right",
    options: ["right", "write", "rice", "ride"], ja: "角を右に曲がってください",
    es: "Gira a la derecha en la esquina" },
  { grade: 4, text: "Go ___ this street.", answer: "along",
    options: ["along", "alone", "aloud", "already"], ja: "この道にそって進んでください",
    es: "Sigue por esta calle" },
  { grade: 4, text: "___ the third floor, please.", answer: "To",
    options: ["To", "At", "In", "On"], ja: "3階までお願いします",
    es: "A la tercera planta, por favor" },
  { grade: 4, text: "What ___ do you like? — I like summer.", answer: "season",
    options: ["season", "reason", "season's", "seasons'"], ja: "どの季節がすきですか",
    es: "¿Qué estación te gusta?" },
  { grade: 4, text: "What ___ is it today? — It's Friday.", answer: "day",
    options: ["day", "date", "time", "week"], ja: "今日は何曜日ですか",
    es: "¿Qué día es hoy?" },
  { grade: 4, text: "I want ___ apple, please.", answer: "an",
    options: ["an", "a", "the", "of"], ja: "りんごを1つください",
    es: "Quiero una manzana, por favor" },
  { grade: 4, text: "I have ___ homework today.", answer: "some",
    options: ["some", "many", "a few", "few"], ja: "今日は宿題があります",
    es: "Hoy tengo deberes" },
  { grade: 4, text: "___ are my shoes.", answer: "These",
    options: ["These", "This", "That", "It"], ja: "これらはわたしのくつです",
    es: "Estos son mis zapatos" },
  { grade: 4, text: "Don't ___ in the library.", answer: "run",
    options: ["run", "runs", "ran", "running"], ja: "図書館では走らないで",
    es: "No corras en la biblioteca" },
  { grade: 4, text: "Let's ___ lunch together.", answer: "have",
    options: ["have", "has", "had", "having"], ja: "いっしょにお昼を食べよう",
    es: "Vamos a comer juntos" },
  { grade: 4, text: "I like dogs ___ cats.", answer: "and",
    options: ["and", "but", "or", "so"], ja: "犬もねこもすきです",
    es: "Me gustan los perros y los gatos" },
  { grade: 4, text: "I like tea, ___ I don't like coffee.", answer: "but",
    options: ["but", "and", "so", "if"], ja: "お茶はすきですが、コーヒーはすきではありません",
    es: "Me gusta el té, pero no me gusta el café" },
  { grade: 4, text: "It's cold, ___ close the window.", answer: "so",
    options: ["so", "but", "or", "if"], ja: "寒いので、窓を閉めましょう",
    es: "Hace frío, así que cierra la ventana" },
  { grade: 4, text: "She is ___ TV now.", answer: "watching",
    options: ["watching", "watch", "watches", "watched"], ja: "彼女は今テレビを見ています",
    es: "Ella está viendo la tele ahora" },
  { grade: 4, text: "They ___ playing in the yard.", answer: "are",
    options: ["are", "is", "am", "be"], ja: "彼らは庭で遊んでいます",
    es: "Ellos están jugando en el patio" },
  { grade: 4, text: "___ you help me? — Sure.", answer: "Can",
    options: ["Can", "Are", "Do you can", "Is"], ja: "手伝ってくれますか",
    es: "¿Me puedes ayudar?" },
  { grade: 4, text: "This is ___ book, not yours.", answer: "her",
    options: ["her", "she", "hers of", "she's"], ja: "これは彼女の本で、あなたのではありません",
    es: "Este es su libro, no el tuyo" },
  { grade: 4, text: "Where ___ your parents? — They're at home.", answer: "are",
    options: ["are", "is", "am", "be"], ja: "ご両親はどこですか",
    es: "¿Dónde están tus padres?" },
  { grade: 4, text: "What ___ do you want to be? — A doctor.", answer: "job",
    options: ["job", "work", "thing", "place"], ja: "何の仕事につきたいですか",
    es: "¿De qué quieres trabajar?" },
  { grade: 5, text: "I ___ to Kyoto last year.", answer: "went",
    options: ["went", "go", "goes", "going"], ja: "去年京都に行きました",
    es: "El año pasado fui a Kioto" },
  { grade: 5, text: "I ___ soccer yesterday.", answer: "played",
    options: ["played", "play", "plays", "playing"], ja: "きのうサッカーをしました",
    es: "Ayer jugué al fútbol" },
  { grade: 5, text: "It ___ fun.", answer: "was",
    options: ["was", "is", "were", "be"], ja: "楽しかったです",
    es: "Fue divertido" },
  { grade: 5, text: "We ___ happy to see you.", answer: "were",
    options: ["were", "was", "are", "be"], ja: "あなたに会えてうれしかったです",
    es: "Nos alegramos de verte" },
  { grade: 5, text: "I ___ eat natto, but now I like it.", answer: "didn't",
    options: ["didn't", "don't", "wasn't", "haven't"], ja: "昔は納豆を食べませんでしたが、今はすきです",
    es: "Antes no comía natto, pero ahora me gusta" },
  { grade: 5, text: "I'm going ___ study English tonight.", answer: "to",
    options: ["to", "for", "at", "of"], ja: "今夜英語を勉強するつもりです",
    es: "Esta noche voy a estudiar inglés" },
  { grade: 5, text: "I ___ like some water, please.", answer: "would",
    options: ["would", "will", "am", "do"], ja: "お水をいただけますか",
    es: "Querría un poco de agua, por favor" },
  { grade: 5, text: "This cake is ___ than that one.", answer: "sweeter",
    options: ["sweeter", "sweet", "sweetest", "more sweet"], ja: "このケーキはあれよりあまいです",
    es: "Este pastel es más dulce que aquel" },
  { grade: 5, text: "Ken runs ___ fast as Yuki.", answer: "as",
    options: ["as", "so", "too", "very"], ja: "ケンはユキと同じくらい速く走ります",
    es: "Ken corre tan rápido como Yuki" },
  { grade: 5, text: "I like winter ___ I can ski.", answer: "because",
    options: ["because", "but", "or", "so that"], ja: "スキーができるので冬がすきです",
    es: "Me gusta el invierno porque puedo esquiar" },
  { grade: 5, text: "I visited my grandmother ___ Sunday.", answer: "last",
    options: ["last", "next", "this coming", "tomorrow"], ja: "先週の日曜日に祖母をたずねました",
    es: "El domingo pasado visité a mi abuela" },
  { grade: 5, text: "My birthday is the ___ of May.", answer: "third",
    options: ["third", "three", "threeth", "thirdth"], ja: "たんじょう日は5月3日です",
    es: "Mi cumpleaños es el tres de mayo" },
  { grade: 5, text: "I want to visit Australia ___ I like animals.", answer: "because",
    options: ["because", "but", "though", "until"], ja: "動物がすきなのでオーストラリアに行きたいです",
    es: "Quiero visitar Australia porque me gustan los animales" },
  { grade: 5, text: "She is good ___ cooking.", answer: "at",
    options: ["at", "in", "on", "of"], ja: "彼女は料理が得意です",
    es: "A ella se le da bien cocinar" },
  { grade: 5, text: "How ___ is the tower? — About 300 meters.", answer: "tall",
    options: ["tall", "long", "much", "many"], ja: "そのタワーはどのくらいの高さですか",
    es: "¿Qué altura tiene la torre?" },
  { grade: 5, text: "___ you like some tea? — Yes, please.", answer: "Would",
    options: ["Would", "Are", "Do", "Can"], ja: "お茶はいかがですか",
    es: "¿Le apetece un té?" },
  { grade: 5, text: "I'd like to ___ a table for two.", answer: "book",
    options: ["book", "take", "make up", "put"], ja: "2名で席を予約したいです",
    es: "Querría reservar una mesa para dos" },
  { grade: 5, text: "Can you tell me ___ to get to the museum?", answer: "how",
    options: ["how", "what", "who", "which"], ja: "博物館への行き方を教えてもらえますか",
    es: "¿Me puedes decir cómo llegar al museo?" },
  { grade: 5, text: "I enjoyed ___ with my friends.", answer: "talking",
    options: ["talking", "talk", "talked", "to talk"], ja: "友だちと話すのを楽しみました",
    es: "Disfruté hablando con mis amigos" },
  { grade: 5, text: "My dream is to ___ a vet.", answer: "become",
    options: ["become", "becomes", "becoming", "became"], ja: "わたしの夢はじゅう医になることです",
    es: "Mi sueño es ser veterinario" },
  { grade: 5, text: "There ___ many people at the festival.", answer: "were",
    options: ["were", "was", "are", "is"], ja: "祭りにはたくさんの人がいました",
    es: "Había mucha gente en la fiesta" },
  { grade: 6, text: "This is the ___ movie I have ever seen.", answer: "best",
    options: ["best", "good", "better", "more good"], ja: "これは今まで見た中でいちばんよい映画です",
    es: "Esta es la mejor película que he visto nunca" },
  { grade: 6, text: "Mt. Fuji is the ___ mountain in Japan.", answer: "highest",
    options: ["highest", "high", "higher", "more high"], ja: "富士山は日本でいちばん高い山です",
    es: "El monte Fuji es la montaña más alta de Japón" },
  { grade: 6, text: "I have ___ been to Okinawa.", answer: "never",
    options: ["never", "ever", "yet", "already"], ja: "沖縄には行ったことがありません",
    es: "Nunca he estado en Okinawa" },
  { grade: 6, text: "Have you ___ finished your homework? — Yes, I have.", answer: "already",
    options: ["already", "yet", "never", "ago"], ja: "もう宿題を終えましたか",
    es: "¿Ya has terminado los deberes?" },
  { grade: 6, text: "I ___ studying English for three years.", answer: "have been",
    options: ["have been", "am", "was", "had"], ja: "3年間英語を勉強しています",
    es: "Llevo tres años estudiando inglés" },
  { grade: 6, text: "The letter ___ written by my father.", answer: "was",
    options: ["was", "did", "has", "were"], ja: "その手紙は父によって書かれました",
    es: "La carta fue escrita por mi padre" },
  { grade: 6, text: "English is ___ in many countries.", answer: "spoken",
    options: ["spoken", "speak", "speaking", "spoke"], ja: "英語は多くの国で話されています",
    es: "El inglés se habla en muchos países" },
  { grade: 6, text: "If you ___ hard, you will pass the test.", answer: "study",
    options: ["study", "studies", "studied", "studying"], ja: "一生けんめい勉強すれば、テストに合格するでしょう",
    es: "Si estudias mucho, aprobarás el examen" },
  { grade: 6, text: "I think ___ this book is interesting.", answer: "that",
    options: ["that", "what", "which", "who"], ja: "この本はおもしろいと思います",
    es: "Creo que este libro es interesante" },
  { grade: 6, text: "The boy ___ is running is my brother.", answer: "who",
    options: ["who", "which", "whose", "whom"], ja: "走っている男の子はわたしの兄弟です",
    es: "El niño que está corriendo es mi hermano" },
  { grade: 6, text: "I want to be a teacher ___ help children.", answer: "to",
    options: ["to", "for", "so", "that"], ja: "子どもを助けるために先生になりたいです",
    es: "Quiero ser profesor para ayudar a los niños" },
  { grade: 6, text: "It is important ___ read books.", answer: "to",
    options: ["to", "for", "of", "at"], ja: "本を読むことは大切です",
    es: "Es importante leer libros" },
  { grade: 6, text: "I'm looking forward ___ seeing you.", answer: "to",
    options: ["to", "for", "at", "on"], ja: "お会いするのを楽しみにしています",
    es: "Tengo muchas ganas de verte" },
  { grade: 6, text: "She asked me ___ I liked sushi.", answer: "if",
    options: ["if", "that", "so", "or"], ja: "彼女はわたしにすしがすきかたずねました",
    es: "Ella me preguntó si me gustaba el sushi" },
  { grade: 6, text: "My town is famous ___ its old temple.", answer: "for",
    options: ["for", "of", "at", "with"], ja: "わたしの町は古い寺で有名です",
    es: "Mi pueblo es famoso por su templo antiguo" },
  { grade: 6, text: "We should ___ care of the environment.", answer: "take",
    options: ["take", "make", "do", "give"], ja: "わたしたちは環境を大切にすべきです",
    es: "Deberíamos cuidar el medio ambiente" },
  { grade: 6, text: "You ___ not eat in the classroom.", answer: "must",
    options: ["must", "can", "will", "would"], ja: "教室で食べてはいけません",
    es: "No se puede comer en el aula" },
  { grade: 6, text: "I ___ to finish this report by Friday.", answer: "have",
    options: ["have", "must", "should", "can"], ja: "金曜日までにこの報告を終えなければなりません",
    es: "Tengo que terminar este informe antes del viernes" },
  { grade: 6, text: "Could you ___ that again, please?", answer: "say",
    options: ["say", "tell", "speak", "talk"], ja: "もう一度言っていただけますか",
    es: "¿Podría repetirlo, por favor?" },
  { grade: 6, text: "___ don't we go to the beach?", answer: "Why",
    options: ["Why", "How", "What", "When"], ja: "海に行きませんか",
    es: "¿Por qué no vamos a la playa?" },
  { grade: 6, text: "I was ___ when I heard the news.", answer: "surprised",
    options: ["surprised", "surprising", "surprise", "surprises"], ja: "その知らせを聞いておどろきました",
    es: "Me sorprendí cuando escuché la noticia" },
  { grade: 6, text: "Kyoto is worth ___.", answer: "visiting",
    options: ["visiting", "visit", "to visit", "visited"], ja: "京都はたずねる価値があります",
    es: "Kioto merece la pena visitarlo" },
];
